name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  basic-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sanity check
        run: echo "Build OK ✅"
